controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\LoginController::index

app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard